### ISSUE TITLE
Xml parse error with empty element of type xsd:string

### ISSUE THREAD

**Issue by olafklinke** [mlabs-haskell/opc-xml-da-client#17]
The following should return the empty text but fails.
```
{-# LANGUAGE OverloadedStrings #-}
import OpcXmlDaClient.Protocol.XmlParsing
import XmlParser
import Data.ByteString (ByteString)
import Data.Text (Text)
emptyString = "<Value xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" xsi:type=\"xsd:string\"></Value>" :: ByteString
parseByteString value emptyString -- fails with "no nodes left"
```
The reason is that for xsd:string the definition of `value` is essentially this:
```
textElt = children $ contentNode textContent :: Element Text
```
but `emptyString` has no children. Insert any text in the Value tag and the parser succeeds.

**Comment by blamario** [comment]
I don't see anything wrong with this behaviour as far as XML goes, but I'm not familiar with the OPC spec. Can you point to the section of the spec that explains this?

**Comment by olafklinke** [comment]
The OPC spec has nothing to do with this. Attached is part of a BrowseResponse from an OPC server which is not parsed by opc-xml-da-client because a Value element with type annotation xsd:string (thus a general xml string type) and no content is not parsed.                    
```
<Properties
                        xsi:type="ns1:ItemProperty"
                        Description="Item value"
                        ItemName="Alias"
                        Name="ns1:value"
                        ItemPath="Loc/Wec/Plant1/">
                        <Value
                            xsi:type="xsd:string">
                            </Value>
</Properties>
```

**Comment by olafklinke** [comment]
This is linked to an issue in [xml-parser](https://github.com/nikita-volkov/xml-parser/issues/1) which when resolved can help implement a fix.

**Comment by nikita-volkov** [comment]
I'll address it in xml-parser

**Comment by nikita-volkov** [comment]
It's been addressed in xml-parser-0.1.1.

**Comment by olafklinke** [comment]
The issue seems to be fixed in [xml-parser-0.1.1](https://github.com/nikita-volkov/xml-parser/actions/runs/1807602780). Please update the cabal file to use xml-parser >= 0.1.1, then test my above code. If that does not throw an error, please increase this package's version number and close the issue.

**Comment by nikita-volkov** [comment]
@blamario Can you do this?

**Comment by blamario** [comment]
Yes, just not right now.

**Comment by blamario** [comment]
Who's the client, where do I Harvest this?

**Comment by nikita-volkov** [comment]
The client is Westfalen Wind.

The presented code is already tested here: https://github.com/nikita-volkov/xml-parser/commit/fffb206d2d59bdf3340e609e8f5db0efaa2f8e5c. So it seems like all we need is a version bump. And I'm pushing it now.

**Comment by olafklinke** [comment]
Please also bump the version of opc-xml-da-client so that downstream packages can make sure that this fixed xml-parser is used.

**Comment by nikita-volkov** [comment]
@olafklinke I'm lacking rights to upload to Hackage. Can you add me? My username is NikitaVolkov there
